 출처 : https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3) # 초기화 되지 않은 5 x 3 형태를 만들기, 할당된 메모리에 존재하는 값들이 나타남
print(x)

tensor([[1.3517e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [3.7293e-08, 3.9664e+28, 6.9397e+22],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])


In [4]:
x = torch.rand(5,3) # 초기화 되어 랜덤 값 5 x 3 형태의 tensor 만들어줌
print(x)

tensor([[0.7048, 0.3276, 0.9853],
        [0.9783, 0.6705, 0.3701],
        [0.9617, 0.4039, 0.1340],
        [0.4263, 0.2244, 0.7150],
        [0.5999, 0.7073, 0.3677]])


In [5]:
x = torch.zeros(5,3,dtype = torch.long) # torch.long 은 float , long 이 없으면 int 값을
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype = torch.double) 
print(x)

x = torch.rand_like(x, dtype = torch.float) # 결과는 동일한 크기이나 dtype 이 바뀜
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.9203, 0.7810, 0.7339],
        [0.8864, 0.9373, 0.1744],
        [0.7761, 0.8656, 0.5302],
        [0.2183, 0.3864, 0.7933],
        [0.7252, 0.5913, 0.6310]])


In [10]:
print(x.size()) # 튜플 타입

torch.Size([5, 3])


## 연산 operations

In [11]:
y = torch.rand(5,3)
print(x + y)

tensor([[1.1647, 1.5561, 1.1011],
        [1.2429, 1.6265, 0.3457],
        [1.4130, 0.9352, 0.7865],
        [0.8533, 0.6929, 0.9228],
        [1.0372, 0.8900, 1.2666]])


In [12]:
print(torch.add(x, y))

tensor([[1.1647, 1.5561, 1.1011],
        [1.2429, 1.6265, 0.3457],
        [1.4130, 0.9352, 0.7865],
        [0.8533, 0.6929, 0.9228],
        [1.0372, 0.8900, 1.2666]])


In [13]:
result = torch.empty(5,3)
torch.add(x, y, out = result)

print(result)

tensor([[1.1647, 1.5561, 1.1011],
        [1.2429, 1.6265, 0.3457],
        [1.4130, 0.9352, 0.7865],
        [0.8533, 0.6929, 0.9228],
        [1.0372, 0.8900, 1.2666]])


In [15]:
# 만약 inplace 바식으로 한다면?
y.add_(x) # y.add(x) 가 아니라, y.add_(x) 처럼 작성해야 함
print(y)

tensor([[2.0850, 2.3370, 1.8351],
        [2.1293, 2.5638, 0.5201],
        [2.1891, 1.8008, 1.3168],
        [1.0716, 1.0792, 1.7161],
        [1.7624, 1.4813, 1.8976]])


In [16]:
print(x[:, 1])

tensor([0.7810, 0.9373, 0.8656, 0.3864, 0.5913])


In [18]:
# 크기 변경을 하고 자 한다면 torch.view 를 사용

x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

print(x, y, z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[0.3152, 0.7128, 0.5267, 0.5925],
        [0.5433, 0.8030, 0.0803, 0.6958],
        [0.4724, 0.6624, 0.7164, 0.1585],
        [0.3620, 0.3553, 0.8669, 0.9914]]) tensor([0.3152, 0.7128, 0.5267, 0.5925, 0.5433, 0.8030, 0.0803, 0.6958, 0.4724,
        0.6624, 0.7164, 0.1585, 0.3620, 0.3553, 0.8669, 0.9914]) tensor([[0.3152, 0.7128, 0.5267, 0.5925, 0.5433, 0.8030, 0.0803, 0.6958],
        [0.4724, 0.6624, 0.7164, 0.1585, 0.3620, 0.3553, 0.8669, 0.9914]])


In [19]:
# 만약 tensor 하나만 존재한다면 .item() 을 사용하여 숫자 값을 얻음

x = torch.rand(1)
print(x)
print(x.item())

tensor([0.2268])
0.2268214225769043


## torch tensor 를 numpy 배열로 변환

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [24]:
a.add_(1) # a 의 모든 원소에 1을 더함
print(a)
print(b) # b 는 a.numpy() 로 생겨먹었는데, a 만 바뀌면 b는 저절로 변경됨

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


## Numpy 배열을 torch tensor 로 변형
- np 배열을 변경하면 torch tensor 값도 자동 변경

In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## cuda tensor
- .to 메소드 사용하여 tensor 옮길 수 있다

In [27]:
# cuda 사용할 수 있다면, torch.device() 를 통해 gpu 를 사용할 지, cpu 를 사용할 지 구분 가능
if torch.cuda.is_available():
    device = torch.device('cuda') # cuda 장치 객체로 gpu 상에 직접 tensor 를 생성
    y = torch.ones_like(x, device = device)
    x = x.to(device) # 혹은 .to('cuda') 를 사용함
    z = x + y
    print(z)
    print(z.to('cpu', torch.double)) # .to() 는 dtype 도 함께 변경

## Autograd 자동 미분
- tensor 모든 연산에 자동 미분을 함

### tensor
- requires_grad  = True 하면, tensor 통해 이루어진 모든 연산을 추적한다
- 완료 시 .backward() 호출하면 gradient 자동으로 계산 가능 : .grad 속성에 누적
- 도중에 추적을 멈추고자 한다면 .detach() 호출하여 연산 기록에서 분리

- with torch.no_grad(): 로 감싼다면 기록 추적 방지